version: '3.8'

services:
  mongo-db:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONgit push -f origin masterGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
     - ./mongo:/data/db  
    ports:
     - 27017:27017
